version: "3"
services:
    redis:
        image: redis:latest
        volumes:
            - ./example_config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        restart: always
        networks:
            - intelmq-internal
    nginx:
        image: certat/intelmq-nginx:latest
        restart: always
        ports:
            - 1337:80
        depends_on:
            - intelmq
        networks:
            - intelmq-internal
    intelmq:
        image: certat/intelmq-full:latest
        volumes:
            - ./example_config/intelmq/etc/:/opt/intelmq/etc/
            - ./example_config/intelmq-api/config.json:/etc/intelmq/api-config.json
            - ./intelmq_logs:/opt/intelmq/var/log
            - ./intelmq_output:/opt/intelmq/var/lib/bots

            - ./custom_bots/ecs/expert:/usr/local/bin/intelmq.bots.experts.ecs.expert:rx
            - ./custom_bots/ecs/expert.py:/etc/intelmq/intelmq/bots/experts/ecs/expert.py:ro
        depends_on:
            - redis
        environment:
            INTELMQ_SOURCE_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_BROKER: "redis"
            INTELMQ_DESTIONATION_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_HOST: redis
            INTELMQ_SOURCE_PIPELINE_HOST: redis
            INTELMQ_DESTINATION_PIPELINE_HOST: redis
            INTELMQ_REDIS_CACHE_HOST: redis
        networks:
            - intelmq-internal

networks:
    intelmq-internal:
        driver: bridge
